name: CI/CD

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install npm deps
        run: pnpm install --frozen-lockfile

      - name: Check the build
        run: pnpm run check

      - name: Code linting
        run: pnpm run lint

      # This is a workaround until https://github.com/webpro/knip/issues/565 gets resolved
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Check dependencies and unused files
        run: bunx --bun knip

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run integration tests
        run: pnpm run test:integration

      - name: Build package
        run: pnpm run package

      - name: Validate package exports
        run: |
          # Test that the package can be packed
          npm pack --dry-run

          # Verify tree-shaking exports work correctly
          node -e "
            const pkg = require('./package.json');
            const exports = Object.keys(pkg.exports);
            console.log('✅ Package exports validated:', exports.length, 'exports');
            
            // Check that key components are exported
            const requiredExports = ['./button', './badge', './input'];
            const missing = requiredExports.filter(exp => !exports.includes(exp));
            if (missing.length > 0) {
              console.error('❌ Missing required exports:', missing);
              process.exit(1);
            }
            console.log('✅ All required exports present');
          "
